In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [3]:
data_1 = pd.read_csv('homework_3.1.csv')

data_1.head()

   time    value1    value2    value3
0     0  1.764052  1.883151 -0.369182
1     1  0.420157 -1.327759 -0.219379
2     2  1.018738 -1.230485  1.139660
3     3  2.300893  1.029397  0.715264
4     4  1.947558 -1.093123  0.720132

In [4]:
data_1['After'] = (data_1['time'] >= 50).astype(int)
data_1['Time_After'] = (data_1['time'] - 50) * data_1['After']

data_1.head()

   time    value1    value2    value3  After  Time_After
0     0  1.764052  1.883151 -0.369182      0           0
1     1  0.420157 -1.327759 -0.219379      0           0
2     2  1.018738 -1.230485  1.139660      0           0
3     3  2.300893  1.029397  0.715264      0           0
4     4  1.947558 -1.093123  0.720132      0           0

In [5]:
X = data_1[['time', 'After']]
X = sm.add_constant(X)

y = data_1['value1']

model1 = sm.OLS(y, X).fit()

print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 value1   R-squared:                       0.651
Model:                            OLS   Adj. R-squared:                  0.644
Method:                 Least Squares   F-statistic:                     90.57
Date:                Wed, 23 Sep 2026   Prob (F-statistic):           6.48e-23
Time:                        15:07:06   Log-Likelihood:                -160.63
No. Observations:                 100   AIC:                             327.3
Df Residuals:                      97   BIC:                             335.1
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.4439      0.271     -1.640      0.104      -0.981       0.093
time           0.0439      0.008      5.168      0.000       0.027       0.061
After          0.8508      0.490      1.737      0.086      -0.121       1.823
==============================================================================
Omnibus:                        2.006   Durbin-Watson:                   1.316
Prob(Omnibus):                  0.367   Jarque-Bera (JB):                1.444
Skew:                          -0.029   Prob(JB):                        0.486
Kurtosis:                       2.414   Cond. No.                         238.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [6]:
X = data_1[['time', 'After']]
X = sm.add_constant(X)

y = data_1['value2']

model2 = sm.OLS(y, X).fit()

print(model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 value2   R-squared:                       0.540
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     56.92
Date:                Wed, 23 Sep 2026   Prob (F-statistic):           4.44e-17
Time:                        15:07:06   Log-Likelihood:                -146.89
No. Observations:                 100   AIC:                             299.8
Df Residuals:                      97   BIC:                             307.6
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0418      0.236      0.177      0.860      -0.426       0.510
time           0.0288      0.007      3.889      0.000       0.014       0.043
After          0.6827      0.427      1.599      0.113      -0.165       1.530
==============================================================================
Omnibus:                        8.209   Durbin-Watson:                   1.938
Prob(Omnibus):                  0.016   Jarque-Bera (JB):                4.146
Skew:                           0.272   Prob(JB):                        0.126
Kurtosis:                       2.164   Cond. No.                         238.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [7]:
X = data_1[['time', 'After']]
X = sm.add_constant(X)

y = data_1['value3']

model3 = sm.OLS(y, X).fit()

print(model3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 value3   R-squared:                       0.777
Model:                            OLS   Adj. R-squared:                  0.773
Method:                 Least Squares   F-statistic:                     169.3
Date:                Wed, 23 Sep 2026   Prob (F-statistic):           2.33e-32
Time:                        15:07:06   Log-Likelihood:                -141.75
No. Observations:                 100   AIC:                             289.5
Df Residuals:                      97   BIC:                             297.3
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.5235      0.224     -2.337      0.022      -0.968      -0.079
time           0.0363      0.007      5.163      0.000       0.022       0.050
After          1.7673      0.406      4.357      0.000       0.962       2.572
==============================================================================
Omnibus:                        0.491   Durbin-Watson:                   2.116
Prob(Omnibus):                  0.782   Jarque-Bera (JB):                0.190
Skew:                          -0.084   Prob(JB):                        0.909
Kurtosis:                       3.133   Cond. No.                         238.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [8]:
X = data_1[['time', 'After', 'Time_After']]
X = sm.add_constant(X)

y = data_1['value1']

model1 = sm.OLS(y, X).fit()

print(model1.pvalues['Time_After'])

3.6020730449436783e-12

In [9]:
X = data_1[['time', 'After', 'Time_After']]
X = sm.add_constant(X)

y = data_1['value2']

model2 = sm.OLS(y, X).fit()

print(model2.pvalues['Time_After'])

0.011811304711071759

In [10]:
X = data_1[['time', 'After', 'Time_After']]
X = sm.add_constant(X)

y = data_1['value3']

model3 = sm.OLS(y, X).fit()

print(model3.pvalues['Time_After'])

0.00020766104648181657

In [11]:
data2 = pd.read_csv('homework_3.2.a.csv')
data3 = pd.read_csv('homework_3.2.b.csv')

display(data2.head())

display(data3.head())

   group1  time1  outcome1
0       0      0  0.882026
1       0      1  1.600079
2       0      0  0.489369
3       0      1  2.520447
4       0      0  0.933779

   group2  time2  outcome2
0       0      0  0.667155
1       0      1  2.470969
2       0      0 -0.506778
3       0      1  1.525657
4       0      0  0.273664

In [12]:
data2['interaction'] = data2['group1'] * data2['time1']

data3['interaction'] = data3['group2'] * data3['time2']

display(data2.head())
display(data3.head())

   group1  time1  outcome1  interaction
0       0      0  0.882026            0
1       0      1  1.600079            0
2       0      0  0.489369            0
3       0      1  2.520447            0
4       0      0  0.933779            0

   group2  time2  outcome2  interaction
0       0      0  0.667155            0
1       0      1  2.470969            0
2       0      0 -0.506778            0
3       0      1  1.525657            0
4       0      0  0.273664            0

In [13]:
X2 = data2[['group1', 'time1', 'interaction']]
X2 = sm.add_constant(X2)
y2 = data2['outcome1']

X3 = data3[['group2', 'time2', 'interaction']]
X3 = sm.add_constant(X3)
y3 = data3['outcome2']

model2 = sm.OLS(y2, X2).fit()
model3 = sm.OLS(y3, X3).fit()

print(f'The estimated treatment effect for dataset A is {model2.params['interaction']:.2f}')
print(f'The estimated treatment effect for dataset B is {model3.params['interaction']:.2f}')

The estimated treatment effect for dataset A is 0.69
The estimated treatment effect for dataset B is 1.35

In [15]:
display(model2.summary())
display(model3.summary())

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               outcome1   R-squared:                       0.899
Model:                            OLS   Adj. R-squared:                  0.899
Method:                 Least Squares   F-statistic:                     2964.
Date:                Wed, 23 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:12:50   Log-Likelihood:                -712.28
No. Observations:                1000   AIC:                             1433.
Df Residuals:                     996   BIC:                             1452.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -0.0258      0.031     -0.829      0.408      -0.087       0.035
group1          1.9863      0.044     44.928      0.000       1.900       2.073
time1           1.4272      0.044     32.315      0.000       1.341       1.514
interaction     0.6858      0.063     10.970      0.000       0.563       0.809
==============================================================================
Omnibus:                        0.196   Durbin-Watson:                   2.048
Prob(Omnibus):                  0.907   Jarque-Bera (JB):                0.236
Skew:                           0.032   Prob(JB):                        0.889
Kurtosis:                       2.961   Cond. No.                         6.85
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               outcome2   R-squared:                       0.663
Model:                            OLS   Adj. R-squared:                  0.662
Method:                 Least Squares   F-statistic:                     653.6
Date:                Wed, 23 Sep 2026   Prob (F-statistic):          9.62e-235
Time:                        15:12:50   Log-Likelihood:                -1567.5
No. Observations:                1000   AIC:                             3143.
Df Residuals:                     996   BIC:                             3163.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           0.1021      0.073      1.392      0.164      -0.042       0.246
group2          1.8477      0.104     17.770      0.000       1.644       2.052
time2           1.2655      0.104     12.183      0.000       1.062       1.469
interaction     1.3499      0.147      9.180      0.000       1.061       1.638
==============================================================================
Omnibus:                        0.711   Durbin-Watson:                   2.069
Prob(Omnibus):                  0.701   Jarque-Bera (JB):                0.796
Skew:                           0.047   Prob(JB):                        0.672
Kurtosis:                       2.899   Cond. No.                         6.85
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
model2.pvalues['interaction']

np.float64(1.640050300919866e-26)

In [17]:
model3.pvalues['interaction']

np.float64(2.4324361840088903e-19)