In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

data1 = pd.read_csv('homework_8.1.csv')

In [16]:
data1.head()

   X         Y         Z
0  1  4.109218  1.764052
1  0  2.259504  0.400157
2  0 -0.647584  0.978738
3  0  2.106071  2.240893
4  1  3.583464  1.867558

In [17]:
X = data1[['Z']]

y = data1['X']

model_lr = LogisticRegression()

model_lr.fit(X, y)

LogisticRegression()

In [18]:
data1['propensity_score'] = model_lr.predict_proba(X)[:, 1]

data1.head()

   X         Y         Z  propensity_score
0  1  4.109218  1.764052          0.840114
1  0  2.259504  0.400157          0.584646
2  0 -0.647584  0.978738          0.711082
3  0  2.106071  2.240893          0.892793
4  1  3.583464  1.867558          0.853089

In [22]:
weighted_y_treated = []
weighted_y_untreated = []

for i in range(len(data1)):
    if data1.loc[i, 'X'] == 1:
        ipw = 1/data1.loc[i, 'propensity_score']
        weighted_y_treated.append(ipw * data1.loc[i, 'Y'])
    else: 
        ipw = 1/(1 - data1.loc[i, 'propensity_score'])
        weighted_y_untreated.append(ipw * data1.loc[i, 'Y'])

ATE = (sum(weighted_y_treated) - sum(weighted_y_untreated))/len(data1)

print(f'The average treatment effect is {ATE:.1f}')

The average treatment effect is 2.2

In [24]:
data2 = pd.read_csv('homework_8.2.csv')

data2.head()

   X         Y        Z1        Z2
0  1  4.652085  1.764052  2.320015
1  1  2.590221  0.400157  1.292631
2  1  3.898981  0.978738  0.556423
3  1  5.857179  2.240893  2.345607
4  1  3.647489  1.867558  2.095611

In [38]:
import scipy

Z_matrix = np.array(data2[['Z1', 'Z2']]).T

cov_matrix = np.cov(Z_matrix)
inv_cov = np.linalg.inv(cov_matrix)

print('Inverted Covariance Matrix')
print(inv_cov)

Inverted Covariance Matrix
[[ 2.02734407 -1.03387633]
 [-1.03387633  1.06684813]]

In [ ]:
untreated_rows = data2[data2['X'] == 0]
treated_rows = data2[data2['X'] == 1]

matches = []

for index, treated in treated_rows.iterrows():

    distances = []

    for idx, untreated in untreated_rows.iterrows():
        distance = scipy.spatial.distance.mahalanobis(treated[['Z1', 'Z2']].to_numpy(dtype = float), untreated[['Z1', 'Z2']].to_numpy(dtype = float),
                                                      inv_cov)
        distances.append(distance)

    nearest_index = np.argmin(distances)

    matches.append((index, untreated_rows.index[nearest_index]))

matches

[(0, np.int64(681)),
 (1, np.int64(752)),
 (2, np.int64(892)),
 (3, np.int64(922)),
 (4, np.int64(922)),
 (5, np.int64(371)),
 (6, np.int64(681)),
 (9, np.int64(381)),
 (10, np.int64(704)),
 (11, np.int64(161)),
 (12, np.int64(764)),
 (13, np.int64(802)),
 (15, np.int64(51)),
 (16, np.int64(922)),
 (19, np.int64(904)),
 (21, np.int64(436)),
 (24, np.int64(161)),
 (26, np.int64(771)),
 (28, np.int64(161)),
 (29, np.int64(123)),
 (30, np.int64(991)),
 (31, np.int64(381)),
 (36, np.int64(436)),
 (37, np.int64(681)),
 (38, np.int64(986)),
 (43, np.int64(161)),
 (53, np.int64(121)),
 (54, np.int64(240)),
 (55, np.int64(381)),
 (57, np.int64(35)),
 (62, np.int64(799)),
 (64, np.int64(698)),
 (66, np.int64(506)),
 (67, np.int64(500)),
 (69, np.int64(226)),
 (72, np.int64(677)),
 (74, np.int64(500)),
 (75, np.int64(124)),
 (79, np.int64(533)),
 (81, np.int64(892)),
 (82, np.int64(217)),
 (84, np.int64(123)),
 (87, np.int64(49)),
 (88, np.int64(461)),
 (89, np.int64(677)),
 (91, np.int64(579)),
 (94, np.int64(269)),
 (95, np.int64(987)),
 (97, np.int64(922)),
 (98, np.int64(226)),
 (99, np.int64(217)),
 (100, np.int64(85)),
 (103, np.int64(362)),
 (105, np.int64(85)),
 (108, np.int64(161)),
 (109, np.int64(681)),
 (110, np.int64(922)),
 (111, np.int64(436)),
 (113, np.int64(85)),
 (114, np.int64(240)),
 (115, np.int64(269)),
 (117, np.int64(302)),
 (118, np.int64(675)),
 (119, np.int64(116)),
 (120, np.int64(370)),
 (125, np.int64(738)),
 (126, np.int64(545)),
 (127, np.int64(922)),
 (128, np.int64(811)),
 (131, np.int64(968)),
 (133, np.int64(866)),
 (134, np.int64(173)),
 (135, np.int64(811)),
 (136, np.int64(764)),
 (138, np.int64(758)),
 (142, np.int64(802)),
 (143, np.int64(204)),
 (144, np.int64(161)),
 (145, np.int64(892)),
 (146, np.int64(772)),
 (147, np.int64(116)),
 (151, np.int64(532)),
 (156, np.int64(677)),
 (158, np.int64(40)),
 (162, np.int64(436)),
 (163, np.int64(407)),
 (165, np.int64(170)),
 (166, np.int64(40)),
 (168, np.int64(677)),
 (169, np.int64(18)),
 (172, np.int64(436)),
 (175, np.int64(987)),
 (179, np.int64(776)),
 (180, np.int64(645)),
 (182, np.int64(58)),
 (187, np.int64(35)),
 (188, np.int64(282)),
 (189, np.int64(123)),
 (191, np.int64(35)),
 (194, np.int64(675)),
 (195, np.int64(776)),
 (196, np.int64(987)),
 (197, np.int64(47)),
 (198, np.int64(397)),
 (199, np.int64(681)),
 (200, np.int64(504)),
 (202, np.int64(161)),
 (203, np.int64(436)),
 (206, np.int64(216)),
 (208, np.int64(758)),
 (210, np.int64(681)),
 (211, np.int64(469)),
 (212, np.int64(764)),
 (218, np.int64(85)),
 (219, np.int64(707)),
 (222, np.int64(645)),
 (224, np.int64(185)),
 (225, np.int64(407)),
 (227, np.int64(749)),
 (233, np.int64(269)),
 (235, np.int64(411)),
 (236, np.int64(681)),
 (239, np.int64(204)),
 (241, np.int64(215)),
 (242, np.int64(866)),
 (244, np.int64(777)),
 (246, np.int64(681)),
 (248, np.int64(409)),
 (250, np.int64(569)),
 (252, np.int64(389)),
 (253, np.int64(553)),
 (254, np.int64(811)),
 (259, np.int64(223)),
 (265, np.int64(674)),
 (267, np.int64(263)),
 (270, np.int64(129)),
 (272, np.int64(161)),
 (273, np.int64(980)),
 (276, np.int64(569)),
 (279, np.int64(161)),
 (280, np.int64(8)),
 (281, np.int64(93)),
 (283, np.int64(681)),
 (285, np.int64(421)),
 (287, np.int64(123)),
 (288, np.int64(968)),
 (289, np.int64(161)),
 (292, np.int64(922)),
 (295, np.int64(123)),
 (296, np.int64(997)),
 (297, np.int64(764)),
 (298, np.int64(392)),
 (299, np.int64(129)),
 (301, np.int64(123)),
 (308, np.int64(217)),
 (311, np.int64(93)),
 (315, np.int64(407)),
 (316, np.int64(820)),
 (318, np.int64(150)),
 (322, np.int64(888)),
 (326, np.int64(520)),
 (327, np.int64(85)),
 (328, np.int64(970)),
 (329, np.int64(170)),
 (330, np.int64(436)),
 (333, np.int64(260)),
 (335, np.int64(569)),
 (337, np.int64(758)),
 (339, np.int64(161)),
 (340, np.int64(247)),
 (343, np.int64(104)),
 (346, np.int64(841)),
 (347, np.int64(704)),
 (348, np.int64(752)),
 (349, np.int64(217)),
 (352, np.int64(681)),
 (354, np.int64(155)),
 (357, np.int64(855)),
 (359, np.int64(569)),
 (360, np.int64(764)),
 (361, np.int64(802)),
 (363, np.int64(752)),
 (367, np.int64(65)),
 (368, np.int64(777)),
 (372, np.int64(170)),
 (375, np.int64(752)),
 (383, np.int64(765)),
 (384, np.int64(533)),
 (388, np.int64(123)),
 (390, np.int64(217)),
 (391, np.int64(378)),
 (396, np.int64(170)),
 (398, np.int64(681)),
 (399, np.int64(22)),
 (402, np.int64(432)),
 (403, np.int64(269)),
 (406, np.int64(436)),
 (408, np.int64(263)),
 (414, np.int64(85)),
 (415, np.int64(762)),
 (416, np.int64(269)),
 (419, np.int64(85)),
 (420, np.int64(93)),
 (425, np.int64(407)),
 (426, np.int64(170)),
 (429, np.int64(405)),
 (430, np.int64(344)),
 (433, np.int64(840)),
 (435, np.int64(675)),
 (437, np.int64(364)),
 (438, np.int64(764)),
 (439, np.int64(758)),
 (440, np.int64(392)),
 (442, np.int64(216)),
 (443, np.int64(637)),
 (444, np.int64(681)),
 (445, np.int64(209)),
 (448, np.int64(523)),
 (449, np.int64(738)),
 (451, np.int64(436)),
 (452, np.int64(381)),
 (453, np.int64(637)),
 (455, np.int64(85)),
 (460, np.int64(645)),
 (464, np.int64(694)),
 (465, np.int64(85)),
 (474, np.int64(922)),
 (475, np.int64(892)),
 (476, np.int64(123)),
 (478, np.int64(681)),
 (479, np.int64(381)),
 (480, np.int64(764)),
 (481, np.int64(93)),
 (484, np.int64(436)),
 (486, np.int64(161)),
 (487, np.int64(752)),
 (488, np.int64(263)),
 (489, np.int64(749)),
 (491, np.int64(314)),
 (492, np.int64(247)),
 (493, np.int64(681)),
 (494, np.int64(418)),
 (495, np.int64(802)),
 (499, np.int64(501)),
 (502, np.int64(681)),
 (503, np.int64(599)),
 (505, np.int64(290)),
 (508, np.int64(121)),
 (509, np.int64(86)),
 (510, np.int64(362)),
 (511, np.int64(161)),
 (516, np.int64(381)),
 (517, np.int64(116)),
 (518, np.int64(955)),
 (519, np.int64(922)),
 (524, np.int64(972)),
 (526, np.int64(116)),
 (527, np.int64(161)),
 (529, np.int64(170)),
 (531, np.int64(752)),
 (538, np.int64(294)),
 (540, np.int64(389)),
 (542, np.int64(34)),
 (543, np.int64(397)),
 (546, np.int64(116)),
 (548, np.int64(247)),
 (549, np.int64(970)),
 (551, np.int64(698)),
 (552, np.int64(436)),
 (555, np.int64(161)),
 (559, np.int64(697)),
 (560, np.int64(161)),
 (565, np.int64(955)),
 (566, np.int64(454)),
 (567, np.int64(968)),
 (568, np.int64(216)),
 (570, np.int64(948)),
 (573, np.int64(432)),
 (574, np.int64(269)),
 (575, np.int64(34)),
 (578, np.int64(949)),
 (587, np.int64(269)),
 (588, np.int64(545)),
 (591, np.int64(500)),
 (594, np.int64(752)),
 (595, np.int64(675)),
 (597, np.int64(520)),
 (601, np.int64(902)),
 (605, np.int64(290)),
 (606, np.int64(656)),
 (608, np.int64(463)),
 (611, np.int64(692)),
 (612, np.int64(376)),
 (613, np.int64(835)),
 (614, np.int64(561)),
 (616, np.int64(515)),
 (617, np.int64(269)),
 (618, np.int64(681)),
 (620, np.int64(47)),
 (623, np.int64(373)),
 (626, np.int64(423)),
 (627, np.int64(681)),
 (629, np.int64(802)),
 (632, np.int64(217)),
 (634, np.int64(855)),
 (635, np.int64(749)),
 (638, np.int64(47)),
 (639, np.int64(86)),
 (640, np.int64(779)),
 (641, np.int64(161)),
 (642, np.int64(706)),
 (646, np.int64(432)),
 (647, np.int64(302)),
 (648, np.int64(60)),
 (649, np.int64(161)),
 (650, np.int64(675)),
 (653, np.int64(752)),
 (654, np.int64(603)),
 (655, np.int64(948)),
 (658, np.int64(44)),
 (659, np.int64(68)),
 (660, np.int64(68)),
 (662, np.int64(806)),
 (664, np.int64(770)),
 (667, np.int64(93)),
 (669, np.int64(902)),
 (678, np.int64(161)),
 (679, np.int64(217)),
 (680, np.int64(694)),
 (682, np.int64(332)),
 (683, np.int64(269)),
 (686, np.int64(922)),
 (688, np.int64(656)),
 (689, np.int64(85)),
 (690, np.int64(652)),
 (691, np.int64(436)),
 (695, np.int64(681)),
 (699, np.int64(681)),
 (703, np.int64(93)),
 (705, np.int64(161)),
 (708, np.int64(397)),
 (711, np.int64(811)),
 (714, np.int64(123)),
 (715, np.int64(949)),
 (718, np.int64(170)),
 (719, np.int64(665)),
 (722, np.int64(802)),
 (726, np.int64(673)),
 (727, np.int64(579)),
 (728, np.int64(170)),
 (729, np.int64(223)),
 (732, np.int64(240)),
 (734, np.int64(85)),
 (736, np.int64(764)),
 (737, np.int64(307)),
 (742, np.int64(161)),
 (743, np.int64(7)),
 (747, np.int64(762)),
 (748, np.int64(692)),
 (750, np.int64(332)),
 (753, np.int64(532)),
 (754, np.int64(216)),
 (755, np.int64(332)),
 (756, np.int64(811)),
 (757, np.int64(576)),
 (761, np.int64(972)),
 (766, np.int64(776)),
 (767, np.int64(209)),
 (768, np.int64(85)),
 (769, np.int64(645)),
 (773, np.int64(389)),
 (775, np.int64(610)),
 (780, np.int64(922)),
 (781, np.int64(269)),
 (784, np.int64(238)),
 (785, np.int64(226)),
 (787, np.int64(675)),
 (791, np.int64(209)),
 (793, np.int64(922)),
 (796, np.int64(666)),
 (800, np.int64(681)),
 (801, np.int64(811)),
 (803, np.int64(44)),
 (804, np.int64(892)),
 (807, np.int64(501)),
 (809, np.int64(216)),
 (812, np.int64(436)),
 (813, np.int64(228)),
 (814, np.int64(14)),
 (815, np.int64(532)),
 (816, np.int64(240)),
 (817, np.int64(85)),
 (822, np.int64(702)),
 (826, np.int64(454)),
 (827, np.int64(922)),
 (828, np.int64(161)),
 (829, np.int64(906)),
 (830, np.int64(902)),
 (831, np.int64(835)),
 (832, np.int64(821)),
 (833, np.int64(366)),
 (834, np.int64(821)),
 (838, np.int64(902)),
 (842, np.int64(362)),
 (843, np.int64(161)),
 (844, np.int64(141)),
 (846, np.int64(811)),
 (848, np.int64(152)),
 (849, np.int64(294)),
 (857, np.int64(986)),
 (860, np.int64(93)),
 (862, np.int64(561)),
 (864, np.int64(709)),
 (869, np.int64(362)),
 (870, np.int64(681)),
 (874, np.int64(764)),
 (876, np.int64(845)),
 (878, np.int64(389)),
 (880, np.int64(681)),
 (882, np.int64(738)),
 (883, np.int64(294)),
 (884, np.int64(207)),
 (886, np.int64(411)),
 (887, np.int64(44)),
 (889, np.int64(467)),
 (891, np.int64(269)),
 (893, np.int64(866)),
 (895, np.int64(85)),
 (896, np.int64(523)),
 (898, np.int64(161)),
 (899, np.int64(545)),
 (903, np.int64(562)),
 (905, np.int64(681)),
 (908, np.int64(22)),
 (909, np.int64(922)),
 (912, np.int64(677)),
 (914, np.int64(920)),
 (915, np.int64(706)),
 (916, np.int64(802)),
 (918, np.int64(217)),
 (921, np.int64(397)),
 (923, np.int64(698)),
 (924, np.int64(374)),
 (925, np.int64(161)),
 (927, np.int64(645)),
 (928, np.int64(675)),
 (929, np.int64(681)),
 (930, np.int64(681)),
 (935, np.int64(910)),
 (937, np.int64(85)),
 (940, np.int64(752)),
 (941, np.int64(436)),
 (942, np.int64(217)),
 (943, np.int64(85)),
 (946, np.int64(972)),
 (947, np.int64(161)),
 (951, np.int64(861)),
 (952, np.int64(397)),
 (954, np.int64(805)),
 (956, np.int64(170)),
 (958, np.int64(161)),
 (961, np.int64(436)),
 (962, np.int64(18)),
 (963, np.int64(269)),
 (966, np.int64(666)),
 (967, np.int64(161)),
 (969, np.int64(987)),
 (971, np.int64(93)),
 (973, np.int64(681)),
 (974, np.int64(85)),
 (975, np.int64(713)),
 (976, np.int64(34)),
 (979, np.int64(621)),
 (981, np.int64(424)),
 (982, np.int64(837)),
 (983, np.int64(93)),
 (988, np.int64(532)),
 (990, np.int64(675)),
 (992, np.int64(910)),
 (993, np.int64(888)),
 (994, np.int64(18)),
 (995, np.int64(381)),
 (996, np.int64(520))]