In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

data1 = pd.read_csv('homework_4.1.csv')

In [2]:
data1.head()

   Z         W         X         Y
0  0 -0.155644 -0.496971  0.282484
1  1  0.529539  2.284240  4.740596
2  1  0.910514  0.872232  3.449569
3  1 -0.705476  2.157260  3.002531
4  0 -0.590874 -0.386730 -1.848796

In [4]:
y_mean1 = data1.loc[data1['Z'] == 1, 'Y'].mean()
y_mean0 = data1.loc[data1['Z'] == 0, 'Y'].mean()

x_mean1 = data1.loc[data1['Z'] == 1, 'X'].mean()
x_mean0 = data1.loc[data1['Z'] == 0, 'X'].mean()

effect1 = (y_mean1 - y_mean0)/(x_mean1 - x_mean0)

print(f"The first calculated effect is: {effect1 :.1f}.")

The first calculated effect is: 1.6.

In [13]:
data1['w_range'] = pd.cut(data1['W'], bins = 10)

effects = []

for w_range, group in data1.groupby('w_range', observed = True):

    y_mean1 = group.loc[group['Z'] == 1, 'Y'].mean()
    y_mean0 = group.loc[group['Z'] == 0, 'Y'].mean()

    x_mean1 = group.loc[group['Z'] == 1, 'X'].mean()
    x_mean0 = group.loc[group['Z'] == 0, 'X'].mean()

    y_diff = y_mean1 - y_mean0
    x_diff = x_mean1 - x_mean0

    if x_diff != 0 and pd.notna(x_diff) and pd.notna(y_diff): 
        effect = y_diff/x_diff

        effects.append(effect)

overall_effect = np.mean(effects)

print(f"The overall mean for the second task is {overall_effect :.2f}.")

The overall mean for the second task is 0.91.

In [14]:
data2 = pd.read_csv('homework_4.2.a.csv')
data3 = pd.read_csv('homework_4.2.b.csv')

display(data2.head())
display(data3.head())

           X  Y
0  81.822339  1
1  92.487870  0
2  85.372460  0
3  78.828025  0
4  75.807080  1

          X2  Y2
0  76.643034   1
1  87.743397   1
2  81.639469   1
3  73.740485   0
4  90.480268   1

In [16]:
data2['treated'] = (data2['X'] >= 80).astype(int)
data2['X_centered'] = data2['X'] - 80
data2['interaction'] = data2['treated'] * data2['X_centered']

data3['treated'] = (data3['X2'] >= 80).astype(int)
data3['X_centered'] = data3['X2'] - 80
data3['interaction'] = data3['treated'] * data3['X_centered']

X1 = data2[['treated', 'X_centered', 'interaction']]
X1 = sm.add_constant(X1)
y1 = data2['Y']

X2 = data3[['treated', 'X_centered', 'interaction']]
X2 = sm.add_constant(X2)
y2 = data3['Y2']

model1 = sm.OLS(y1, X1).fit()
model2 = sm.OLS(y2, X2).fit()

display(model1.summary())
display(model2.summary())

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.090
Model:                            OLS   Adj. R-squared:                  0.090
Method:                 Least Squares   F-statistic:                     3300.
Date:                Tue, 29 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:55:43   Log-Likelihood:                -67412.
No. Observations:              100000   AIC:                         1.348e+05
Df Residuals:                   99996   BIC:                         1.349e+05
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           0.3050      0.004     86.481      0.000       0.298       0.312
treated         0.2958      0.005     58.270      0.000       0.286       0.306
X_centered      0.0002      0.000      0.635      0.525      -0.000       0.001
interaction -6.274e-05      0.001     -0.121      0.904      -0.001       0.001
==============================================================================
Omnibus:                   510375.147   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10775.665
Skew:                           0.159   Prob(JB):                         0.00
Kurtosis:                       1.424   Cond. No.                         42.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     Y2   R-squared:                       0.160
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     6360.
Date:                Tue, 29 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:55:43   Log-Likelihood:                -45123.
No. Observations:              100000   AIC:                         9.025e+04
Df Residuals:                   99996   BIC:                         9.029e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const           0.7023      0.003    249.432      0.000       0.697       0.708
treated         0.1971      0.004     48.474      0.000       0.189       0.205
X_centered      0.0102      0.000     36.324      0.000       0.010       0.011
interaction    -0.0052      0.000    -12.529      0.000      -0.006      -0.004
==============================================================================
Omnibus:                    11036.340   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14927.338
Skew:                          -0.940   Prob(JB):                         0.00
Kurtosis:                       2.773   Cond. No.                         42.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""