In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data_1 = pd.read_csv("homework_1.1.csv")

data_1.head()

         X1        X2        X3          Y
0 -0.440646 -0.390227  0.156718  -0.877671
1 -3.810099 -1.304665 -1.105117 -10.130388
2 -1.425451 -0.340049  1.115908   0.284068
3 -1.325750  0.161906 -0.254670  -1.994344
4  3.120263  1.487343 -1.164839   2.030030

In [ ]:
# Multiple Regression on all Xs
import statsmodels.api as sm

X = data_1.drop(columns = ['Y'])
X = sm.add_constant(X)
Y = data_1['Y']

model = sm.OLS(Y, X).fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                 3.543e+04
Date:                Fri, 04 Sep 2026   Prob (F-statistic):               0.00
Time:                        15:44:19   Log-Likelihood:                -727.62
No. Observations:                1000   AIC:                             1463.
Df Residuals:                     996   BIC:                             1483.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0026      0.016      0.166      0.868      -0.029       0.034
X1             1.0071      0.017     60.984      0.000       0.975       1.040
X2             1.9646      0.037     53.283      0.000       1.892       2.037
X3             2.9755      0.015    196.645      0.000       2.946       3.005
==============================================================================
Omnibus:                        0.655   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.721   Jarque-Bera (JB):                0.592
Skew:                          -0.058   Prob(JB):                        0.744
Kurtosis:                       3.029   Cond. No.                         5.94
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# Single Regression for each Xs
X1 = data_1[['X1']]
X1 = sm.add_constant(X1)

X2 = data_1[['X2']]
X2 = sm.add_constant(X2)

X3 = data_1[['X3']]
X3 = sm.add_constant(X3)

model1 = sm.OLS(Y, X1).fit()
t_val1 = model1.tvalues
coef_1 = model1.params

model2 = sm.OLS(Y, X2).fit()
t_val2 = model2.tvalues
coef_2 = model2.params

model3 = sm.OLS(Y, X3).fit()
t_val3 = model3.tvalues
coef_3 = model3.params

print(f"X1 T-Value: {t_val1['X1']:.2f}, X1 Coefficient: {coef_1['X1']:.2f}")
print(f'X2 T-Value: {t_val2['X2']:.2f}, X2 Coefficient: {coef_2['X2']:.2f}')
print(f'X3 T-Value: {t_val3['X3']:.2f}, X3 Coefficient: {coef_3['X3']:.2f}')

X1 T-Value: 38.88, X1 Coefficient: 1.84
X2 T-Value: 38.22, X2 Coefficient: 4.08
X3 T-Value: 25.31, X3 Coefficient: 3.10

In [16]:
data2 = pd.read_csv('homework_1.2.csv')

data2.head()

   X         Y         Z
0  0  0.548814  0.548814
1  1  1.215189  0.715189
2  0  0.602763  0.602763
3  0  0.544883  0.544883
4  0  0.423655  0.423655

In [ ]:
# Fitting the nearest neighbors
from sklearn.neighbors import NearestNeighbors

nbrs = NearestNeighbors(n_neighbors = 1)

X_0 = data2[data2['X'] == 0]
X_1 = data2[data2['X'] == 1]

nbrs.fit(X_0[['Z']])

distances, indices = nbrs.kneighbors(X_1[['Z']])

In [ ]:
# Closest Distance between Matches
min(distances)

array([0.00038939])

In [ ]:
# Furthest Distance between Matches (Question 4)
max(distances)

array([0.21021709])

In [ ]:
# Answering Question 5
matched_X0 = X_0.iloc[indices.flatten()]

avg_y_1 = X_1['Y'].mean()
avg_y_matched0 = matched_X0['Y'].mean()

effect_a = avg_y_1 - avg_y_matched0

print(f"The effect is {effect_a:.5f}.")

The effect is 0.54336.

In [ ]:
# Using radius neighbors to get matches within 0.2
nbrs_b = NearestNeighbors(radius = 0.2)

nbrs_b.fit(X_0[['Z']])

distances, indices = nbrs_b.radius_neighbors(X_1[['Z']])

In [ ]:
# Getting the number of duplicates

all_indices = np.concatenate(indices)

duplicates = pd.Series(all_indices).value_counts()

print(f"Number of duplicates: {sum(duplicates) - 52}")

Number of duplicates: 685

In [80]:
# Calculating the Effect of Approach B

approach_b_means = []

for i in indices:
    if len(i) > 0: 
        approach_b_means.append(X_0.iloc[i]['Y'].mean())

approach_b_means[0:5]

[np.float64(0.6163863470681296),
 np.float64(0.5934840103439379),
 np.float64(0.4439765329199784),
 np.float64(0.7445825114889059),
 np.float64(0.7781567509498505)]

In [83]:
overall_mean = np.mean(approach_b_means)

effect_b = avg_y_1 - overall_mean

print(f"The effect for Approach B is {effect_b:.4f}.")

The effect for Approach B is 0.5844.