In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

data1 = pd.read_csv("homework_2.1.csv")

In [3]:
data1.head()

   time        G1        G2        G3
0     0  0.882026  1.441575  0.065409
1     1  0.210079 -0.163880  0.140310
2     2  0.509369 -0.115242  0.819830
3     3  1.150447  1.014698  0.607632
4     4  0.973779 -0.046562  0.610066

In [4]:
X1 = data1['G1']

X2 = data1['G2']

X3 = data1['G3']

y = data1["time"]
y = sm.add_constant(y)

model1 = sm.OLS(X1, y).fit()
coef1 = model1.params

model2 = sm.OLS(X2, y).fit()
coef2 = model2.params

model3 = sm.OLS(X3, y).fit()
coef3 = model3.params

print(f"G1 Coefficient: {coef1.iloc[1]:.5f}")
print(f"G2 Coefficient: {coef2.iloc[1]:.5f}")
print(f"G3 Coefficient: {coef3.iloc[1]:.5f}")

G1 Coefficient: 0.00850
G2 Coefficient: 0.00708
G3 Coefficient: 0.01147

In [ ]:
x_mean = data1['time'].mean()

y_means = {'G1' : data1['G1'].mean(), 'G2' : data1['G2'].mean(), 'G3' : data1['G3'].mean()}

y_values = []
x_values = []

for i in range(3):
    x_values.extend(data1['time'] - x_mean)

for i in y_means.keys():
    y_values.extend(data1[i] - y_means[i])

print(len(x_values))
print(len(y_values))

300
300

In [ ]:
data = {'time' : x_values, 'groups' : y_values}

final_data = pd.DataFrame(data)

final_data.head()

   time    groups
0 -49.5  0.357122
1 -48.5 -0.314825
2 -47.5 -0.015535
3 -46.5  0.625543
4 -45.5  0.448875

In [17]:
x = final_data['time']
x = sm.add_constant(x)

y = final_data['groups']

model = sm.OLS(y, x).fit()

model.params

const    1.040834e-17
time     9.017213e-03
dtype: float64

In [7]:
data2 = pd.read_csv("homework_2.2.csv")

data2.head()

   X          Y         Z
0  0   1.182435 -0.725820
1  0   2.714474  0.563476
2  0   0.077612 -0.435632
3  0  -0.154449 -0.104553
4  0  22.298992 -2.321273

In [22]:
effects = []

for i in range(1000):

    sample = data2.sample(n = len(data2), replace = True)

    treated_mean = sample[sample['X'] == 1]['Y'].mean()
    untreated_mean = sample[sample['X'] == 0]['Y'].mean()

    effects.append(treated_mean - untreated_mean)

mean_effect = np.mean(effects)
var_effect = np.var(effects, ddof = 1)

print(f'The mean effect by subtracting is {mean_effect:.3f}.')
print(f'The variance of effect by subtracting is {var_effect:.6f}.')

The mean effect by subtracting is 2.918.
The variance of effect by subtracting is 0.031345.

In [34]:
from scipy.stats import skew

effect = []

for i in range(100000):

    sample = data2.sample(n = len(data2), replace = True)

    X = sample['X']
    X = sm.add_constant(X)

    y = sample['Y']

    model = sm.OLS(y, X).fit()

    effect.append(model.params['X'])

effect_skewness = skew(effect)

print(f'The skewness of the measured effect is {effect_skewness:.5f}.')

The skewness of the measured effect is 0.03523.